dist: trusty

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "nikitazhidov" # the key of the org you chose at step #3

script:
  - qmake
  - make
  - ./tests/tests
  
after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  #- build-wrapper-win-x86-64.exe --out-dir  build_wrapper_output_directory build-wrapper-win-x86-64 /t:Rebuildl
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner 


notifications:
  email: "false"

