dist: trusty

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "nikitazhidov" # the key of the org you chose at step #3

script:
  - qmake
  - make
  - ./tests/tests
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output 
  

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
 
notifications:
  email: false

